"""Generated by `python -m omezarr_view.bundle`. Do not edit.

The HTML under frontend/ is the source of truth; this exists so the
pages reach a BioEngine replica, which only receives Python modules.
"""

PAGES = {
    'index.html': r'''<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>OME-Zarr views over existing files</title>
<style>
  :root {
    --bg: #fbfbfd;
    --panel: #ffffff;
    --ink: #16181d;
    --ink-2: #5c626e;
    --ink-3: #8b90a0;
    --line: #e6e7ec;
    --line-2: #f0f1f5;
    --accent: #4338ca;
    --accent-soft: #eef0ff;
    --local: #0f766e;
    --local-soft: #e6f5f2;
    --remote: #a1560a;
    --remote-soft: #fdf1e0;
    --radius: 14px;
    --mono: ui-monospace, SFMono-Regular, "SF Mono", Menlo, Consolas, monospace;
  }
  @media (prefers-color-scheme: dark) {
    :root {
      --bg: #0d0e12; --panel: #15171d; --ink: #eceef4; --ink-2: #a2a8b8;
      --ink-3: #6f7688; --line: #262932; --line-2: #1d2028;
      --accent: #a5b4fc; --accent-soft: #1e2140;
      --local: #5eead4; --local-soft: #10312e;
      --remote: #fbbf24; --remote-soft: #33260c;
    }
  }
  * { box-sizing: border-box; }
  [hidden] { display: none !important; }
  html { -webkit-text-size-adjust: 100%; }
  body {
    margin: 0; background: var(--bg); color: var(--ink);
    font: 15px/1.6 -apple-system, BlinkMacSystemFont, "Segoe UI", Inter, Roboto,
          Helvetica, Arial, sans-serif;
    -webkit-font-smoothing: antialiased;
  }
  .wrap { max-width: 1120px; margin: 0 auto; padding: 0 24px 96px; }

  header { padding: 72px 0 40px; border-bottom: 1px solid var(--line); }
  .eyebrow {
    font: 600 11px/1 var(--mono); letter-spacing: .14em; text-transform: uppercase;
    color: var(--accent); margin-bottom: 18px;
  }
  h1 {
    margin: 0 0 16px; font-size: clamp(30px, 4.4vw, 46px); line-height: 1.1;
    letter-spacing: -0.025em; font-weight: 640;
  }
  .lede { margin: 0; max-width: 62ch; color: var(--ink-2); font-size: 17px; }
  .lede strong { color: var(--ink); font-weight: 600; }

  .facts { display: flex; flex-wrap: wrap; gap: 10px; margin-top: 28px; }
  .fact {
    border: 1px solid var(--line); background: var(--panel); border-radius: 999px;
    padding: 6px 14px; font-size: 12.5px; color: var(--ink-2);
  }
  .fact b { color: var(--ink); font-weight: 600; font-variant-numeric: tabular-nums; }

  h2 {
    font-size: 13px; font-weight: 640; letter-spacing: .08em; text-transform: uppercase;
    color: var(--ink-3); margin: 52px 0 4px;
  }
  .section-note { margin: 0 0 20px; color: var(--ink-2); font-size: 14px; max-width: 68ch; }

  .grid { display: grid; gap: 18px; grid-template-columns: repeat(auto-fill, minmax(330px, 1fr)); }

  .card {
    background: var(--panel); border: 1px solid var(--line); border-radius: var(--radius);
    overflow: hidden; display: flex; flex-direction: column;
    transition: border-color .18s ease, transform .18s ease;
  }
  .card:hover { border-color: var(--ink-3); }

  .thumb {
    aspect-ratio: 16 / 9; background: var(--line-2); position: relative;
    display: grid; place-items: center; overflow: hidden;
  }
  .thumb img { width: 100%; height: 100%; object-fit: cover; display: block; }
  .thumb .ph { color: var(--ink-3); font: 500 12px/1 var(--mono); letter-spacing: .06em; }

  .badges { position: absolute; top: 10px; left: 10px; display: flex; gap: 6px; }
  .badge {
    font: 600 10.5px/1 var(--mono); letter-spacing: .06em; text-transform: uppercase;
    padding: 5px 8px; border-radius: 6px; backdrop-filter: blur(6px);
  }
  .badge.local { background: var(--local-soft); color: var(--local); }
  .badge.remote { background: var(--remote-soft); color: var(--remote); }
  .badge.computed { background: var(--accent-soft); color: var(--accent); }
  .badge.fmt { background: var(--accent-soft); color: var(--accent); }
  .badge.lock { background: var(--accent-soft); color: var(--accent); }

  .body { padding: 18px 18px 16px; display: flex; flex-direction: column; gap: 12px; flex: 1; }
  .title { font-size: 16px; font-weight: 620; letter-spacing: -0.01em; margin: 0; }
  .src {
    font: 11.5px/1.5 var(--mono); color: var(--ink-3); word-break: break-all;
    margin: 0; max-height: 3em; overflow: hidden;
  }

  dl.specs { margin: 0; display: grid; grid-template-columns: auto 1fr; gap: 4px 14px; font-size: 13px; }
  dl.specs dt { color: var(--ink-3); }
  dl.specs dd { margin: 0; font-variant-numeric: tabular-nums; }
  dl.specs code { font: 12px/1.5 var(--mono); }

  .actions { display: flex; gap: 8px; margin-top: auto; padding-top: 4px; flex-wrap: wrap; }
  button, a.btn {
    font: 500 13px/1 inherit; padding: 9px 13px; border-radius: 9px; cursor: pointer;
    border: 1px solid var(--line); background: var(--panel); color: var(--ink);
    text-decoration: none; display: inline-flex; align-items: center; gap: 6px;
    transition: background .15s ease, border-color .15s ease;
  }
  button:hover, a.btn:hover { border-color: var(--ink-3); }
  button.primary, a.btn.primary {
    background: var(--accent); border-color: var(--accent); color: #fff;
  }
  @media (prefers-color-scheme: dark) {
    button.primary, a.btn.primary { color: #14162b; }
  }
  button.primary:hover, a.btn.primary:hover { filter: brightness(1.08); }
  button:disabled { opacity: .5; cursor: not-allowed; }

  .status { font-size: 12.5px; color: var(--ink-2); min-height: 1.5em; }
  .status .ok { color: var(--local); font-weight: 600; }
  .status .err { color: #dc2626; }

  details { border-top: 1px solid var(--line-2); padding-top: 10px; }
  details summary {
    cursor: pointer; font-size: 12.5px; color: var(--ink-2); list-style: none;
    display: flex; align-items: center; gap: 6px; user-select: none;
  }
  details summary::-webkit-details-marker { display: none; }
  details summary::before { content: "▸"; color: var(--ink-3); transition: transform .15s; }
  details[open] summary::before { transform: rotate(90deg); }
  details .inner { padding: 10px 0 2px; font-size: 12.5px; color: var(--ink-2); }
  ul.map { margin: 6px 0 0; padding-left: 18px; }
  ul.map li { margin-bottom: 3px; }
  ul.map li.yes::marker { content: "✓ "; color: var(--local); }
  ul.map li.no::marker { content: "– "; color: var(--ink-3); }
  .timing { font: 12px/1.7 var(--mono); }
  .timing span { color: var(--ink); float: right; }

  .toast {
    position: fixed; bottom: 24px; left: 50%; transform: translate(-50%, 80px);
    background: var(--ink); color: var(--bg); padding: 11px 20px; border-radius: 10px;
    font-size: 13.5px; opacity: 0; transition: all .25s cubic-bezier(.2,.8,.2,1);
    pointer-events: none; z-index: 50;
  }
  .toast.show { opacity: 1; transform: translate(-50%, 0); }

  footer {
    margin-top: 64px; padding-top: 24px; border-top: 1px solid var(--line);
    font-size: 13px; color: var(--ink-3);
  }
  footer a { color: var(--ink-2); }
  .empty { color: var(--ink-3); font-size: 14px; padding: 32px 0; }
</style>
</head>
<body>
<div class="wrap">
  <header>
    <div class="eyebrow">BioEngine · data access</div>
    <h1>Your existing images,<br />served as OME-Zarr.</h1>
    <p class="lede">
      Nothing here was converted. Each file below stays exactly where it is — a
      CZI on local disk, a 42&nbsp;GB OME-TIFF in a public bucket — and BioEngine
      serves a <strong>lazy OME-Zarr view</strong> over it, reading only the
      bytes a client actually asks for. Open one in a viewer, or copy its URL
      into your own code.
    </p>
    <div class="facts" id="facts"></div>
  </header>

  <h2>Local files</h2>
  <p class="section-note">
    A folder on the server's disk. Point it at your own archive and every
    readable file in it gets a view.
  </p>
  <div class="grid" id="grid-local"></div>

  <h2>Remote files</h2>
  <p class="section-note">
    Never downloaded. The view is an index of byte ranges into the original
    object, so reads go straight to the bucket.
  </p>
  <div class="grid" id="grid-remote"></div>

  <h2>Derived views</h2>
  <p class="section-note">
    Computed from a view above, per request — rescaled, channel-selected,
    normalised into what a model wants to be fed. The original file is still
    never rewritten, but unlike the views above these pixels are
    <strong>computed, not the source's own</strong>.
  </p>
  <div class="grid" id="grid-derived"></div>

  <footer>
    <p>
      Views are built on first use — that is the measurement the demo is making,
      so the build time you see on a card is real, not cached from earlier.
      Building a view reads the file's headers, not its pixels; the one
      exception is a single coarse level sampled to pick a sensible display
      range, since these files carry no display settings of their own. Each
      card's detail panel says exactly what it read.
    </p>
    <p id="foot-licence"></p>
  </footer>
</div>
<div class="toast" id="toast"></div>

<script>
const $ = (s, r = document) => r.querySelector(s);
const toastEl = $("#toast");
let toastTimer;
function toast(msg) {
  toastEl.textContent = msg;
  toastEl.classList.add("show");
  clearTimeout(toastTimer);
  toastTimer = setTimeout(() => toastEl.classList.remove("show"), 2200);
}

const fmtBytes = (n) => {
  if (!n && n !== 0) return "—";
  const u = ["B", "KB", "MB", "GB", "TB"];
  let i = 0, v = n;
  while (v >= 1024 && i < u.length - 1) { v /= 1024; i++; }
  return `${v >= 100 || i === 0 ? Math.round(v) : v.toFixed(1)} ${u[i]}`;
};
const fmtShape = (shape, axes) =>
  !shape ? "—" : shape.map((n, i) => `${axes ? axes[i].toLowerCase() : ""}${n}`).join(" × ");
const suffix = (src) => {
  const m = (src || "").toLowerCase().match(/\.(ome\.tiff?|tiff?|czi|nd2|lif|lsm|btf)$/);
  return m ? m[1].replace("ome.", "OME-").toUpperCase() : "IMAGE";
};

function pixelSize(d) {
  const p = d.metadata_mapping?.mapped?.physical_pixel_sizes;
  if (!p) return null;
  const part = (k) => p[k] ? `${(+p[k].size).toFixed(3).replace(/0+$/, "").replace(/\.$/, "")}` : null;
  const xy = part("x") && part("y") && p.x.size === p.y.size ? `${part("x")} µm` :
             [part("x"), part("y")].filter(Boolean).join(" × ") + " µm";
  const z = part("z") ? `, z ${part("z")} µm` : "";
  return xy + z;
}

function mappingList(d) {
  const m = d.metadata_mapping;
  if (!m) return "";
  const yes = Object.entries(m.mapped || {}).map(([k, v]) => {
    const val = typeof v === "object" ? "" : ` — <code>${v}</code>`;
    return `<li class="yes">${k.replace(/_/g, " ")}${val}</li>`;
  });
  const no = (m.not_mapped || []).map((s) => `<li class="no">${s}</li>`);
  return `<ul class="map">${yes.join("")}${no.join("")}</ul>`;
}

function captionBlock(d) {
  // Generated prose, quoted verbatim in figure captions — shown here so what
  // the paper says and what the server did cannot drift apart.
  if (!d.caption) return "";
  const parts = [d.caption.access, d.caption.mapped, d.caption.not_mapped]
    .filter(Boolean).map((t) => `<p style="margin:0 0 8px">${t}</p>`).join("");
  return `<div style="border-left:2px solid var(--line);padding-left:12px;margin-bottom:12px">${parts}</div>`;
}

function timingList(d) {
  const t = d.build_timings_s;
  if (!t) return "";
  const rows = Object.entries(t)
    .map(([k, v]) => `${k.replace(/_s$/, "").replace(/_/g, " ")}<span>${v.toFixed(3)} s</span>`)
    .join("<br />");
  const reads = d.build_reads ? `<p style="margin:8px 0 0">Read to build: ${d.build_reads}.</p>` : "";
  return `<div class="timing">${rows}</div>${reads}`;
}

function card(d) {
  const el = document.createElement("article");
  el.className = "card";
  const isLocal = d.location === "local";
  const isComputed = d.location === "computed";
  el.innerHTML = `
    <div class="thumb" data-thumb>
      <span class="ph">not indexed</span>
      <div class="badges">
        <span class="badge ${isComputed ? "computed" : isLocal ? "local" : "remote"}">${
          isComputed ? "computed" : isLocal ? "local" : "remote"}</span>
        ${isComputed ? "" : `<span class="badge fmt">${suffix(d.source)}</span>`}
        ${d.protected ? '<span class="badge lock">token</span>' : ""}
      </div>
    </div>
    <div class="body">
      <h3 class="title">${d.title}</h3>
      <p class="src">${d.source || (d.protected ? "path withheld until unlocked" : "")}</p>
      <dl class="specs" data-specs></dl>
      <div class="status" data-status></div>
      <div class="actions">
        <button class="primary" data-build>Build view</button>
        <button data-copy>Copy URL</button>
        <a class="btn" data-vizarr target="_blank" rel="noopener">Vizarr ↗</a>
        <a class="btn" data-ng target="_blank" rel="noopener">Neuroglancer ↗</a>
        <a class="btn" data-annotate target="_blank" rel="noopener">Annotate ↗</a>
        <button data-unlock hidden>Unlock</button>
      </div>
      <details data-details hidden>
        <summary>What this view maps, and what it does not</summary>
        <div class="inner" data-inner></div>
      </details>
    </div>`;

  const unlockBtn = el.querySelector("[data-unlock]");
  const ngEl = el.querySelector("[data-ng]");
  const annEl = el.querySelector("[data-annotate]");
  const statusEl = el.querySelector("[data-status]");
  const specsEl = el.querySelector("[data-specs]");
  const buildBtn = el.querySelector("[data-build]");
  const vizarrEl = el.querySelector("[data-vizarr]");
  const detailsEl = el.querySelector("[data-details]");

  // A viewer appends chunk keys to the store root, so a ?token= query would
  // sit before the key and every chunk would 404. Protected views are handed
  // out with the token as a path prefix instead.
  const zarrUrl = () => d.token
    ? d.zarr_url.replace("/zarr/", `/t/${encodeURIComponent(d.token)}/zarr/`)
    : d.zarr_url;
  // Neuroglancer takes its whole state in the fragment. It reads NGFF axes and
  // scales but not the OME display windows, so the contrast measured for this
  // view is passed explicitly — otherwise 16-bit data opens near black.
  const ngUrl = () => {
    const win = d.metadata_mapping && d.omero_window;
    const layer = { type: "image", name: d.id, source: `zarr://${zarrUrl()}` };
    if (win) layer.shaderControls = { normalized: { range: [win.start, win.end] } };
    const state = { layers: [layer], layout: "xy", showDefaultAnnotations: false };
    return "https://neuroglancer-demo.appspot.com/#!" + encodeURIComponent(JSON.stringify(state));
  };
  const refreshLinks = () => {
    vizarrEl.href = `https://hms-dbmi.github.io/vizarr/?source=${zarrUrl()}`;
    ngEl.href = ngUrl();
    annEl.href = `annotate?dataset=${encodeURIComponent(d.id)}` +
      (d.token ? `&token=${encodeURIComponent(d.token)}` : "");
  };
  refreshLinks();
  el.querySelector("[data-copy]").onclick = async () => {
    await navigator.clipboard.writeText(zarrUrl());
    toast(d.token ? "URL copied (includes access token)" : "OME-Zarr URL copied");
  };

  const renderSpecs = (dd) => {
    const rows = [
      ["Dimensions", dd.shape ? `<code>${fmtShape(dd.shape, dd.axes)}</code>` : null],
      ["Data type", dd.dtype ? `<code>${dd.dtype}</code>` : null],
      ["Pyramid", dd.levels ? `${dd.levels} level${dd.levels > 1 ? "s" : ""}` : null],
      ["Chunk", dd.chunks ? `<code>${dd.chunks.join("×")}</code>` : null],
      ["Pixel size", pixelSize(dd)],
      ["Derived from", dd.derived_from ? `<code>${dd.derived_from}</code>` : null],
      ["Transform", dd.transform_chain
        ? dd.transform_chain.map((t) => `<div>${t}</div>`).join("") : null],
      ["Reads source", Array.isArray(dd.source_level_read)
        ? `level ${dd.source_level_read.join(", ")} of the source pyramid` : null],
      ["Source cache", dd.source_chunk_cache && dd.source_chunk_cache.hit_rate !== null
        ? `${(dd.source_chunk_cache.hit_rate * 100).toFixed(0)}% chunk hit rate ` +
          `(${dd.source_chunk_cache.source_chunk_hits} hits, ` +
          `${dd.source_chunk_cache.source_chunk_misses} misses)` : null],
      ["File size", dd.size_bytes ? fmtBytes(dd.size_bytes) : null],
      ["Licence", dd.licence],
    ].filter(([, v]) => v);
    specsEl.innerHTML = rows.map(([k, v]) => `<dt>${k}</dt><dd>${v}</dd>`).join("");
  };
  renderSpecs(d);

  const applyIndexed = (dd) => {
    Object.assign(d, dd);
    renderSpecs(d);
    const t = Object.values(d.build_timings_s || {}).reduce((a, b) => a + b, 0);
    statusEl.innerHTML =
      `<span class="ok">Ready</span> — built in ${t.toFixed(1)} s. ` +
      `${d.recipe_label || ""}`;
    buildBtn.textContent = "Rebuild";
    buildBtn.disabled = false;
    detailsEl.hidden = false;
    el.querySelector("[data-inner]").innerHTML =
      captionBlock(d) + timingList(d) + mappingList(d);
    const thumb = el.querySelector("[data-thumb]");
    const img = new Image();
    img.onload = () => { thumb.querySelector(".ph")?.remove(); thumb.prepend(img); };
    img.onerror = () => { const ph = thumb.querySelector(".ph"); if (ph) ph.textContent = "no preview"; };
    img.src = `api/datasets/${d.id}/thumbnail.png` +
      (d.token ? `?token=${encodeURIComponent(d.token)}` : "");
    img.alt = d.title;
  };

  const build = async () => {
    buildBtn.disabled = true;
    buildBtn.textContent = "Building…";
    statusEl.textContent = "Reading headers from the original file…";
    const t0 = performance.now();
    try {
      const r = await fetch(`api/datasets/${d.id}` +
        (d.token ? `?token=${encodeURIComponent(d.token)}` : ""));
      if (!r.ok) throw new Error((await r.json()).detail || r.statusText);
      const dd = await r.json();
      applyIndexed(dd);
      statusEl.innerHTML += ` <span style="color:var(--ink-3)">(${
        ((performance.now() - t0) / 1000).toFixed(1)} s wall)</span>`;
    } catch (e) {
      statusEl.innerHTML = `<span class="err">${e.message}</span>`;
      buildBtn.textContent = "Retry";
      buildBtn.disabled = false;
    }
  };
  buildBtn.onclick = build;

  const unlock = async () => {
    const supplied = prompt(`Access token for "${d.title}"`);
    if (!supplied) return;
    const r = await fetch(
      `api/datasets/${d.id}?token=${encodeURIComponent(supplied)}`);
    if (!r.ok) { toast("Token rejected"); return; }
    d.token = supplied;
    const dd = await r.json();
    unlockBtn.hidden = true;
    buildBtn.hidden = false;
    el.querySelector("[data-copy]").hidden = false;
    vizarrEl.hidden = false;
    el.querySelector(".badge.lock").textContent = "unlocked";
    refreshLinks();
    applyIndexed(dd);
    toast("Unlocked — links now carry the token");
  };
  unlockBtn.onclick = unlock;

  if (d.redacted) {
    unlockBtn.hidden = false;
    buildBtn.hidden = true;
    el.querySelector("[data-copy]").hidden = true;
    vizarrEl.hidden = true;
    statusEl.innerHTML =
      "<span style=\"color:var(--accent)\">Access controlled</span> — the " +
      "catalog will not describe this image, let alone serve it, without a token.";
  } else if (d.indexed) {
    applyIndexed(d);
  }
  return el;
}

(async () => {
  const r = await fetch("api/datasets");
  const { datasets, title } = await r.json();
  document.title = title;

  const local = datasets.filter((d) => d.location === "local");
  const remote = datasets.filter((d) => d.location === "remote");
  const put = (sel, list) => {
    const g = $(sel);
    if (!list.length) {
      g.innerHTML = '<p class="empty">Nothing configured here yet.</p>';
      return;
    }
    list.forEach((d) => g.appendChild(card(d)));
  };
  put("#grid-local", local);
  put("#grid-remote", remote);
  put("#grid-derived", datasets.filter((d) => d.location === "computed"));

  const totalBytes = datasets.reduce((a, d) => a + (d.size_bytes || 0), 0);
  $("#facts").innerHTML = [
    `<b>${datasets.length}</b> files`,
    `<b>${local.length}</b> local · <b>${remote.length}</b> remote · ` +
      `<b>${datasets.filter((d) => d.location === "computed").length}</b> derived`,
    `<b>${fmtBytes(totalBytes)}</b> of source data`,
    `<b>0</b> converted`,
  ].map((t) => `<span class="fact">${t}</span>`).join("");

  const licences = [...new Set(datasets.map((d) => d.licence).filter(Boolean))];
  $("#foot-licence").innerHTML = licences.length
    ? `Demo data licensed ${licences.join(", ")}; attribution on each dataset's detail endpoint.`
    : "";
})();
</script>
</body>
</html>
''',
    'annotate.html': r'''<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>Annotate a lazy OME-Zarr view</title>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/ol@10.3.1/ol.css" />
<style>
  :root {
    --bg:#0d0e12; --panel:#15171d; --ink:#eceef4; --ink-2:#a2a8b8; --ink-3:#6f7688;
    --line:#262932; --accent:#a5b4fc; --accent-soft:#1e2140;
    --mono: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
  }
  * { box-sizing:border-box; }
  body {
    margin:0; height:100vh; display:flex; background:var(--bg); color:var(--ink);
    font:14px/1.5 -apple-system, BlinkMacSystemFont, "Segoe UI", Inter, Roboto, sans-serif;
  }
  #side {
    width:320px; flex:0 0 320px; border-right:1px solid var(--line);
    padding:20px; overflow-y:auto; background:var(--panel);
  }
  #map { flex:1; background:#000; }
  h1 { font-size:16px; margin:0 0 4px; letter-spacing:-.01em; }
  .sub { color:var(--ink-3); font:11px/1.5 var(--mono); word-break:break-all; margin-bottom:18px; }
  h2 { font:600 11px/1 var(--mono); letter-spacing:.1em; text-transform:uppercase;
       color:var(--ink-3); margin:22px 0 10px; }
  button, select {
    font:500 13px/1 inherit; padding:8px 12px; border-radius:8px; cursor:pointer;
    border:1px solid var(--line); background:#1b1e26; color:var(--ink); margin:0 6px 6px 0;
  }
  button:hover { border-color:var(--ink-3); }
  button.on { background:var(--accent-soft); border-color:var(--accent); color:var(--accent); }
  button.primary { background:var(--accent); border-color:var(--accent); color:#14162b; }
  .row { display:flex; align-items:center; gap:8px; margin-bottom:8px; }
  .row label { color:var(--ink-2); font-size:12px; min-width:58px; }
  input[type=range] { flex:1; }
  #status { font-size:12px; color:var(--ink-2); min-height:2.6em; margin-top:10px; }
  #status .ok { color:#5eead4; } #status .err { color:#fca5a5; }
  ul#feats { list-style:none; padding:0; margin:8px 0 0; font:11px/1.6 var(--mono);
             color:var(--ink-2); max-height:180px; overflow-y:auto; }
  ul#feats li { display:flex; justify-content:space-between; border-bottom:1px solid var(--line); padding:3px 0; }
  ul#feats button { padding:1px 6px; font-size:11px; margin:0; }
  .note { font-size:11.5px; color:var(--ink-3); line-height:1.5; margin-top:16px;
          border-top:1px solid var(--line); padding-top:12px; }
</style>
</head>
<body>
<div id="side">
  <h1 id="title">Annotate</h1>
  <div class="sub" id="src"></div>

  <h2>Draw</h2>
  <div>
    <button data-tool="Polygon">Polygon</button>
    <button data-tool="Circle">Box</button>
    <button data-tool="Point">Point</button>
    <button data-tool="none" class="on">Pan</button>
  </div>

  <h2>Plane</h2>
  <div id="sliders"></div>

  <h2>Annotations</h2>
  <div>
    <button class="primary" id="save">Save</button>
    <button id="reload">Reload</button>
    <button id="clear">Clear</button>
  </div>
  <ul id="feats"></ul>
  <div id="status"></div>

  <p class="note">
    Drawn shapes are stored as GeoJSON beside the catalog, in image pixel
    coordinates. The source file is never written to — that is the point of a
    view. Tiles are rendered on demand from the same lazy view a Zarr client
    reads, so nothing here is pre-generated.
  </p>
</div>
<div id="map"></div>

<script src="https://cdn.jsdelivr.net/npm/ol@10.3.1/dist/ol.js"></script>
<script>
const qs = new URLSearchParams(location.search);
const DATASET = qs.get("dataset");
const TOKEN = qs.get("token");
const auth = (u) => TOKEN ? u + (u.includes("?") ? "&" : "?") + "token=" + encodeURIComponent(TOKEN) : u;
const $ = (s) => document.querySelector(s);
let statusTimer;
function say(msg, cls = "") {
  $("#status").innerHTML = cls ? `<span class="${cls}">${msg}</span>` : msg;
  clearTimeout(statusTimer);
  if (cls === "ok") statusTimer = setTimeout(() => ($("#status").textContent = ""), 3000);
}

(async () => {
  if (!DATASET) { say("Add ?dataset=&lt;id&gt; to the URL.", "err"); return; }
  const grid = await (await fetch(auth(`api/datasets/${DATASET}/tilegrid.json`))).json();
  if (grid.detail) { say(grid.detail, "err"); return; }
  $("#title").textContent = DATASET;
  $("#src").textContent = `${grid.width} x ${grid.height} px, ${grid.levels.length} zoom levels`;

  // OpenLayers works in a y-up world; image rows run downward. Mapping the
  // image into [0, -h] x [0, w] keeps pixel coordinates readable: a click at
  // image (x, y) is map (x, -y), so annotations are stored in image pixels.
  const W = grid.width, H = grid.height;
  const extent = [0, -H, W, 0];
  const index = {};           // z / t position
  grid.index_axes.forEach((a) => (index[a] = Math.floor((grid.index_sizes[a] || 1) / 2)));

  const tileGrid = new ol.tilegrid.TileGrid({
    extent, origin: [0, 0], tileSize: grid.tile_size, resolutions: grid.resolutions,
  });
  const source = new ol.source.XYZ({
    tileGrid,
    projection: new ol.proj.Projection({ code: "image", units: "pixels", extent }),
    tileUrlFunction: ([z, x, y]) => {
      const q = new URLSearchParams(index);
      if (TOKEN) q.set("token", TOKEN);
      return `tiles/${DATASET}/${z}/${x}/${y}.png?${q}`;
    },
  });
  const tileLayer = new ol.layer.Tile({ source });

  const features = new ol.source.Vector();
  const vector = new ol.layer.Vector({
    source: features,
    style: new ol.style.Style({
      stroke: new ol.style.Stroke({ color: "#a5b4fc", width: 2 }),
      fill: new ol.style.Fill({ color: "rgba(165,180,252,0.18)" }),
      image: new ol.style.Circle({ radius: 5, fill: new ol.style.Fill({ color: "#a5b4fc" }) }),
    }),
  });

  const map = new ol.Map({
    target: "map",
    layers: [tileLayer, vector],
    view: new ol.View({
      projection: new ol.proj.Projection({ code: "image", units: "pixels", extent }),
      center: [W / 2, -H / 2],
      resolution: grid.resolutions[0],
      resolutions: grid.resolutions,
      extent,
    }),
  });
  map.getView().fit(extent, { size: map.getSize() });

  // -- plane sliders -------------------------------------------------------
  const sl = $("#sliders");
  if (!grid.index_axes.length) sl.innerHTML = '<span style="color:var(--ink-3);font-size:12px">single plane</span>';
  grid.index_axes.forEach((a) => {
    const n = grid.index_sizes[a];
    const row = document.createElement("div");
    row.className = "row";
    row.innerHTML = `<label>${a.toUpperCase()} <span data-v>${index[a]}</span>/${n - 1}</label>
                     <input type="range" min="0" max="${n - 1}" value="${index[a]}" />`;
    row.querySelector("input").oninput = (e) => {
      index[a] = +e.target.value;
      row.querySelector("[data-v]").textContent = index[a];
      source.refresh();
    };
    sl.appendChild(row);
  });

  // -- drawing -------------------------------------------------------------
  let draw = null;
  const setTool = (tool, btn) => {
    document.querySelectorAll("[data-tool]").forEach((b) => b.classList.remove("on"));
    btn.classList.add("on");
    if (draw) { map.removeInteraction(draw); draw = null; }
    if (tool === "none") return;
    draw = new ol.interaction.Draw({
      source: features,
      type: tool === "Circle" ? "Circle" : tool,
      geometryFunction: tool === "Circle" ? ol.interaction.Draw.createBox() : undefined,
    });
    map.addInteraction(draw);
  };
  document.querySelectorAll("[data-tool]").forEach((b) =>
    (b.onclick = () => setTool(b.dataset.tool, b)));

  // -- persistence ---------------------------------------------------------
  const fmt = new ol.format.GeoJSON();
  const listFeatures = () => {
    const items = features.getFeatures();
    $("#feats").innerHTML = items.length
      ? items.map((f, i) => `<li><span>${i + 1}. ${f.getGeometry().getType()}` +
          `${f.get("z") !== undefined ? ` z=${f.get("z")}` : ""}</span>` +
          `<button data-del="${i}">remove</button></li>`).join("")
      : '<li style="border:0;color:var(--ink-3)">none yet</li>';
    $("#feats").querySelectorAll("[data-del]").forEach((b) =>
      (b.onclick = () => { features.removeFeature(items[+b.dataset.del]); listFeatures(); }));
  };
  features.on(["addfeature", "removefeature", "changefeature"], listFeatures);

  const load = async () => {
    const fc = await (await fetch(auth(`api/datasets/${DATASET}/annotations`))).json();
    features.clear();
    if (fc.features?.length) features.addFeatures(fmt.readFeatures(fc));
    listFeatures();
    say(`${fc.features?.length || 0} annotation(s) loaded`, "ok");
  };

  $("#save").onclick = async () => {
    // Stamp the plane each shape was drawn on: a polygon on z=200 means
    // nothing without it.
    features.getFeatures().forEach((f) => {
      Object.entries(index).forEach(([a, v]) => {
        if (f.get(a) === undefined) f.set(a, v);
      });
    });
    const fc = JSON.parse(fmt.writeFeatures(features.getFeatures()));
    fc.properties = { dataset: DATASET, coordinate_space: "image pixels, y negated" };
    const r = await fetch(auth(`api/datasets/${DATASET}/annotations`), {
      method: "PUT", headers: { "Content-Type": "application/json" },
      body: JSON.stringify(fc),
    });
    const out = await r.json();
    say(r.ok ? `Saved ${out.saved} annotation(s).` : (out.detail || "save failed"),
        r.ok ? "ok" : "err");
  };
  $("#reload").onclick = load;
  $("#clear").onclick = () => { features.clear(); listFeatures(); };

  await load();
})().catch((e) => say(e.message, "err"));
</script>
</body>
</html>
''',
}

SOURCE_HASHES = {'index.html': 'd8932bf1d77d6820', 'annotate.html': 'efc7143cad9c9317'}
