"""Bundle the static pages into a Python module.

A BioEngine replica receives app source through Hypha's per-file transport, and
that transport carries Python modules — `frontend/` does not arrive, which is
why the deployed app served a 503 for its own catalog page while the JSON API
worked fine.

The HTML files stay the source of truth. This writes them into `_pages.py` so
they travel with the code, and records a hash of each so a drift between the
two is detectable rather than silent.

    python -m omezarr_view.bundle          # regenerate after editing the HTML
    python -m omezarr_view.bundle --check  # non-zero exit if out of date
"""
from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path

PACKAGE = Path(__file__).resolve().parent
FRONTEND = PACKAGE.parent / "frontend"
TARGET = PACKAGE / "_pages.py"
PAGES = ("index.html", "annotate.html")


def digest(text: str) -> str:
    return hashlib.sha256(text.encode()).hexdigest()[:16]


def render() -> str:
    parts = [
        '"""Generated by `python -m omezarr_view.bundle`. Do not edit.',
        "",
        "The HTML under frontend/ is the source of truth; this exists so the",
        "pages reach a BioEngine replica, which only receives Python modules.",
        '"""',
        "",
        "PAGES = {",
    ]
    hashes = {}
    for name in PAGES:
        text = (FRONTEND / name).read_text()
        hashes[name] = digest(text)
        parts.append(f"    {name!r}: r'''{text}''',")
    parts += ["}", "", f"SOURCE_HASHES = {hashes!r}", ""]
    return "\n".join(parts)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    if args.check:
        try:
            from . import _pages
        except ImportError:
            print("_pages.py missing; run python -m omezarr_view.bundle")
            return 1
        stale = [n for n in PAGES
                 if _pages.SOURCE_HASHES.get(n) != digest((FRONTEND / n).read_text())]
        if stale:
            print("stale bundled pages:", ", ".join(stale))
            return 1
        print("bundled pages match frontend/")
        return 0

    TARGET.write_text(render())
    print(f"wrote {TARGET} ({TARGET.stat().st_size} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
